In [5]:
!pip3 install --upgrade pip

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pip in /opt/homebrew/lib/python3.9/site-packages (22.1.1)
Collecting pip
  Downloading pip-22.2.1-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 13.7 MB/s eta 0:00:00a 0:00:01
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.1.1
    Uninstalling pip-22.1.1:
      Successfully uninstalled pip-22.1.1
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed pip-22.2.1

In [2]:
pip install --upgrade pip setuptools wheel

Collecting pip
  Using cached pip-22.2.1-py3-none-any.whl (2.0 MB)
Collecting setuptools
  Using cached setuptools-63.3.0-py3-none-any.whl (1.2 MB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: pip, setuptools, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed pip-22.2.1 setuptools-63.3.0 wheel-0.37.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-1.4.3-cp38-cp38-macosx_11_0_arm64.whl (10.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 33.5 MB/s eta 0:00:0000:010:01
Requirement already satisfied: python-dateutil>=2.8.1 in ./python-virtual-environments/project_env/lib/python3.8/site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting numpy>=1.20.0
  Downloading numpy-1.23.1-cp38-cp38-macosx_11_0_arm64.whl (13.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 20.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: six>=1.5 in ./python-virtual-environments/project_env/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.23.1 pandas-1.4.3 pytz-2022.1
Note: you may need to restart the kernel to use updated packages.

In [74]:
import pandas as pd
df = pd.read_csv (r'/Users/youssrarebboud/Desktop/PhD/datasets/EventRela.csv')

In [75]:
df['relation'][100].split('|')[0]

'True/Related/Temporality.Before/Relative/Previous/After'

In [76]:
newdata = pd.DataFrame(columns = df.columns.tolist()+['rel1','rel2','rel3'])

In [77]:
len(newdata.columns)

11

In [78]:
for index, row in df.iterrows():
    tmp=row['relation'].split('|')
    relations=[rel for rel in tmp if "True/Related" in rel and not 'Vague' in rel]
    
    if relations:
        newrow=row.tolist()+relations
        while len(newrow)<len(newdata.columns):
            newrow.append(None)
        
        newdata.loc[len(newdata)] = newrow

In [79]:
newdata = newdata.drop('relation', axis=1)

In [80]:
newdata

,evnt1id,evnt1text,evnt1type,evnt2id,evnt2text,evnt2type,docname,rel1,rel2,rel3
0,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E6,behind bars(contexts: A former militant of the...,Justice_Arrest-Jail,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Meet/Relative/After/P...,True/Related/Contingency.Conditionlity/Relativ...,None
1,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E7,murders(contexts: A former militant of the Fre...,Life_Die,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Before/Relative/After...,True/Related/Contingency.Conditionlity/Relativ...,None
2,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E8,left(contexts: A policeman at the scene confir...,Movement_Transport-Person,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Starts/Relative/Inclu...,True/Related/Contingency.Causality/Absolute/Ca...,None
3,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E10,sentenced(contexts: Cipriani was one of four m...,Justice_Sentence,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Before/Relative/After...,True/Related/Contingency.Conditionlity/Relativ...,True/Related/Comparison.Opposite/Absolute/Oppo...
4,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E13,murder(contexts: Cipriani was one of four memb...,Life_Die,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Before/Relative/After...,True/Related/Contingency.Conditionlity/Relativ...,None
...,...,...,...,...,...,...,...,...,...,...
443,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030304.0250.xml,True/Related/Temporality.Meet/Relative/After/P...,None,None
444,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV3,"EasyCinema founder Stelios Haji-Ioannou, who ...",Justice.Sue,AFP_ENG_20030304.0250.xml,True/Related/Contingency.Conditionlity/Relativ...,True/Related/Temporality.Meet/Relative/After/P...,None
445,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV4,debut of easyCinema's first outlet in Milton ...,Business.Start-Org,AFP_ENG_20030304.0250.xml,True/Related/Expansion.Conjunction/Relative/Ge...,None,None
446,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030509.0345-EV3,"EasyCinema founder Stelios Haji-Ioannou, who ...",Justice.Sue,AFP_ENG_20030304.0250.xml,True/Related/Inheritance.Subevent/Relative/Des...,True/Related/Temporality.During/Relative/Inclu...,None
447,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030509.0345-EV4,debut of easyCinema's first outlet in Milton ...,Business.Start-Org,AFP_ENG_20030304.0250.xml,True/Related/Contingency.Conditionlity/Relativ...,True/Related/Temporality.Before/Relative/Previ...,None

In [82]:
newdata.to_csv('newdata.csv', sep='\t')

In [24]:
h

['EventError/    /    /    /    /    ']

In [19]:
data = data.append(row)

/var/folders/yn/342mzbk93q54f6l4fr2xyc780000gn/T/ipykernel_15817/4153375629.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(row)

In [28]:
data.append({'evnt1id':1,'evnt1text':1,'evnt1type':1,'evnt2id':1,'evnt2text':1,'evnt2type':1,'relation':1,'docname':1}, ignore_index = True)

/var/folders/yn/342mzbk93q54f6l4fr2xyc780000gn/T/ipykernel_15817/3123928164.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data.append({'evnt1id':1,'evnt1text':1,'evnt1type':1,'evnt2id':1,'evnt2text':1,'evnt2type':1,'relation':1,'docname':1}, ignore_index = True)

,evnt1id,evnt1text,evnt1type,evnt2id,evnt2text,evnt2type,relation,docname
0,AFP_ENG_20100414.0615-E1,killer(contexts: French far - left killer leav...,Life_Die,AFP_ENG_20100414.0615-E3,left(contexts: A former militant of the French...,Movement_Transport-Person,EventError/ / / / / |,AFP_ENG_20030519.0372.xml
1,1,1,1,1,1,1,1,1

In [36]:
data.loc[len(data)] = [1,2,1,2,1,1,1,1]

In [38]:
data.loc[len(data)] = [1,2,1,2,2,2,2,2]

In [33]:
r.tolist()

['AFP_ENG_20100414.0615-E1',
 'killer(contexts: French far - left killer leaves jail)',
 'Life_Die',
 'AFP_ENG_20100414.0615-E3',
 'left(contexts: A former militant of the French far - left group Action Directe , Georges Cipriani , left prison on parole on Wednesday after 23 years behind bars for two high - profile murders .)',
 'Movement_Transport-Person',
 'EventError/    /    /    /    /    |',
 'AFP_ENG_20030519.0372.xml']

In [39]:
data

,evnt1id,evnt1text,evnt1type,evnt2id,evnt2text,evnt2type,relation,docname
0,AFP_ENG_20100414.0615-E1,killer(contexts: French far - left killer leav...,Life_Die,AFP_ENG_20100414.0615-E3,left(contexts: A former militant of the French...,Movement_Transport-Person,EventError/ / / / / |,AFP_ENG_20030519.0372.xml
1,1,2,1,2,1,1,1,1
2,1,2,1,2,2,2,2,2

In [1]:
import pandas as pd
mydata= pd.read_csv("/Users/youssrarebboud/newdata.csv", sep='\t')

In [2]:
mydata

,Unnamed: 0,evnt1id,evnt1text,evnt1type,evnt2id,evnt2text,evnt2type,docname,rel1,rel2,rel3
0,0,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E6,behind bars(contexts: A former militant of the...,Justice_Arrest-Jail,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Meet/Relative/After/P...,True/Related/Contingency.Conditionlity/Relativ...,NaN
1,1,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E7,murders(contexts: A former militant of the Fre...,Life_Die,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Before/Relative/After...,True/Related/Contingency.Conditionlity/Relativ...,NaN
2,2,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E8,left(contexts: A policeman at the scene confir...,Movement_Transport-Person,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Starts/Relative/Inclu...,True/Related/Contingency.Causality/Absolute/Ca...,NaN
3,3,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E10,sentenced(contexts: Cipriani was one of four m...,Justice_Sentence,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Before/Relative/After...,True/Related/Contingency.Conditionlity/Relativ...,True/Related/Comparison.Opposite/Absolute/Oppo...
4,4,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E13,murder(contexts: Cipriani was one of four memb...,Life_Die,AFP_ENG_20030519.0372.xml,True/Related/Temporality.Before/Relative/After...,True/Related/Contingency.Conditionlity/Relativ...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
443,443,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030304.0250.xml,True/Related/Temporality.Meet/Relative/After/P...,NaN,NaN
444,444,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV3,"EasyCinema founder Stelios Haji-Ioannou, who ...",Justice.Sue,AFP_ENG_20030304.0250.xml,True/Related/Contingency.Conditionlity/Relativ...,True/Related/Temporality.Meet/Relative/After/P...,NaN
445,445,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV4,debut of easyCinema's first outlet in Milton ...,Business.Start-Org,AFP_ENG_20030304.0250.xml,True/Related/Expansion.Conjunction/Relative/Ge...,NaN,NaN
446,446,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030509.0345-EV3,"EasyCinema founder Stelios Haji-Ioannou, who ...",Justice.Sue,AFP_ENG_20030304.0250.xml,True/Related/Inheritance.Subevent/Relative/Des...,True/Related/Temporality.During/Relative/Inclu...,NaN
447,447,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030509.0345-EV4,debut of easyCinema's first outlet in Milton ...,Business.Start-Org,AFP_ENG_20030304.0250.xml,True/Related/Contingency.Conditionlity/Relativ...,True/Related/Temporality.Before/Relative/Previ...,NaN

In [16]:
filter = mydata['rel1'].str.contains('Expansion')

In [17]:
mydata = mydata[~filter]

In [3]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.Starts/Relative/Included_Start/Includes', value='starts', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.Starts/Relative/Includes/Included_Start', value='starts 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.Starts/Relative/Included_Start/Includes', value='starts', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.Starts/Relative/Includes/Included_Start', value='starts 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.Starts/Relative/Included_Start/Includes', value='starts', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.Starts/Relative/Includes/Included_Start', value='starts 2', regex=True)

In [4]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.Before/Relative/Previous/After', value='immediately before', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.Before/Relative/After/Previous', value='immediately before 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.Before/Relative/Previous/After', value='immediately before', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.Before/Relative/After/Previous', value='immediately before 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.Before/Relative/Previous/After', value='immediately before', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.Before/Relative/After/Previous', value='immediately before 2', regex=True)

In [5]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.Meet/Relative/Previous/After', value='meets', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.Meet/Relative/After/Previous', value='meets 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.Meet/Relative/Previous/After', value='meets', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.Meet/Relative/After/Previous', value='meets 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.Meet/Relative/Previous/After', value='meets', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.Meet/Relative/After/Previous', value='meets 2', regex=True)

In [6]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.Finishes/Relative/Includes/Included_End', value='ends', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.Finishes/Relative/Included_End/Includes', value='ends 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.Finishes/Relative/Includes/Included_End', value='ends', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.Finishes/Relative/Included_End/Includes', value='ends 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.Finishes/Relative/Includes/Included_End', value='ends', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.Finishes/Relative/Included_End/Includes', value='ends 2', regex=True)

In [7]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.During/Relative/Includes/Included_IN', value='contains', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.During/Relative/Included_IN/Includes', value='contains 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.During/Relative/Includes/Included_IN', value='contains', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.During/Relative/Included_IN/Includes', value='contains 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.During/Relative/Includes/Included_IN', value='contains', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.During/Relative/Included_IN/Includes', value='contains 2', regex=True)

In [8]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Temporality.equals/    /    /', value='simoultaneous to', regex=True)

mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Temporality.equals/    /    /', value='simoultaneous to', regex=True)

mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Temporality.equals/    /    /', value='simoultaneous to', regex=True)

In [9]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Contingency.Causality/Absolute/Cause/Result', value='causes', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Contingency.Causality/Absolute/Result/Cause', value='causes 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Contingency.Causality/Absolute/Cause/Result', value='causes', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Contingency.Causality/Absolute/Result/Cause', value='causes 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Contingency.Causality/Absolute/Cause/Result', value='causes', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Contingency.Causality/Absolute/Result/Cause', value='causes 2', regex=True)

In [10]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Contingency.Causality/Relative/Cause/Result', value='causes', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Contingency.Causality/Relative/Result/Cause', value='causes 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Contingency.Causality/Relative/Cause/Result', value='causes', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Contingency.Causality/Relative/Result/Cause', value='causes 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Contingency.Causality/Relative/Cause/Result', value='causes', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Contingency.Causality/Relative/Result/Cause', value='causes 2', regex=True)

In [11]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Contingency.Causality/Relative/Cause/Result', value='causes', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Contingency.Causality/Relative/Result/Cause', value='causes 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Contingency.Causality/Relative/Cause/Result', value='causes', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Contingency.Causality/Relative/Result/Cause', value='causes 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Contingency.Causality/Relative/Cause/Result', value='causes', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Contingency.Causality/Relative/Result/Cause', value='causes 2', regex=True)

In [13]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Contingency.Conditionlity/Relative/Emergence/Condition', value='enables', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Contingency.Conditionlity/Relative/Condition/Emergence', value='enables 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Contingency.Conditionlity/Relative/Emergence/Condition', value='enables', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Contingency.Conditionlity/Relative/Condition/Emergence', value='enables 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Contingency.Conditionlity/Relative/Emergence/Condition', value='enables', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Contingency.Conditionlity/Relative/Condition/Emergence', value='enables 2', regex=True)

In [14]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Comparison.Opposite/Absolute/    /    ', value='opposite to', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Comparison.Opposite/Absolute/Opposite/Opposite', value='opposite to 2', regex=True)

mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Comparison.Opposite/Absolute/    /    ', value='opposite to', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Comparison.Opposite/Absolute/Opposite/Opposite', value='opposite to 2', regex=True)

mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Comparison.Opposite/Absolute/    /    ', value='opposite to', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Comparison.Opposite/Absolute/Opposite/Opposite', value='opposite to 2', regex=True)

In [15]:
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Comparison.Negation/Relative/Negation/Initiator', value='alternative to', regex=True)
mydata['rel1'] = mydata['rel1'].replace(to_replace='True/Related/Comparison.Negation/Relative/Initiator/Negation', value='alternative to 2', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Comparison.Negation/Relative/Negation/Initiator', value='alternative to', regex=True)
mydata['rel2'] = mydata['rel2'].replace(to_replace='True/Related/Comparison.Negation/Relative/Initiator/Negation', value='alternative to 2', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Comparison.Negation/Relative/Negation/Initiator', value='alternative to', regex=True)
mydata['rel3'] = mydata['rel3'].replace(to_replace='True/Related/Comparison.Negation/Relative/Initiator/Negation', value='alternative to 2', regex=True)

In [16]:
mydata

,Unnamed: 0,evnt1id,evnt1text,evnt1type,evnt2id,evnt2text,evnt2type,docname,rel1,rel2,rel3
0,0,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E6,behind bars(contexts: A former militant of the...,Justice_Arrest-Jail,AFP_ENG_20030519.0372.xml,meets 2,enables,NaN
1,1,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E7,murders(contexts: A former militant of the Fre...,Life_Die,AFP_ENG_20030519.0372.xml,immediately before 2,enables,NaN
2,2,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E8,left(contexts: A policeman at the scene confir...,Movement_Transport-Person,AFP_ENG_20030519.0372.xml,starts 2,causes,NaN
3,3,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E10,sentenced(contexts: Cipriani was one of four m...,Justice_Sentence,AFP_ENG_20030519.0372.xml,immediately before 2,enables,opposite to 2
4,4,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E13,murder(contexts: Cipriani was one of four memb...,Life_Die,AFP_ENG_20030519.0372.xml,immediately before 2,enables,NaN
...,...,...,...,...,...,...,...,...,...,...,...
443,443,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030304.0250.xml,meets 2,NaN,NaN
444,444,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV3,"EasyCinema founder Stelios Haji-Ioannou, who ...",Justice.Sue,AFP_ENG_20030304.0250.xml,enables,meets 2,NaN
445,445,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV4,debut of easyCinema's first outlet in Milton ...,Business.Start-Org,AFP_ENG_20030304.0250.xml,True/Related/Expansion.Conjunction/Relative/Ge...,NaN,NaN
446,446,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030509.0345-EV3,"EasyCinema founder Stelios Haji-Ioannou, who ...",Justice.Sue,AFP_ENG_20030304.0250.xml,True/Related/Inheritance.Subevent/Relative/Des...,contains 2,NaN
447,447,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030509.0345-EV4,debut of easyCinema's first outlet in Milton ...,Business.Start-Org,AFP_ENG_20030304.0250.xml,enables 2,immediately before,NaN

In [17]:
mydata.to_csv('mapped_data.csv', sep='\t')

In [18]:
mydata

,Unnamed: 0,evnt1id,evnt1text,evnt1type,evnt2id,evnt2text,evnt2type,docname,rel1,rel2,rel3
0,0,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E6,behind bars(contexts: A former militant of the...,Justice_Arrest-Jail,AFP_ENG_20030519.0372.xml,meets 2,enables,NaN
1,1,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E7,murders(contexts: A former militant of the Fre...,Life_Die,AFP_ENG_20030519.0372.xml,immediately before 2,enables,NaN
2,2,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E8,left(contexts: A policeman at the scene confir...,Movement_Transport-Person,AFP_ENG_20030519.0372.xml,starts 2,causes,NaN
3,3,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E10,sentenced(contexts: Cipriani was one of four m...,Justice_Sentence,AFP_ENG_20030519.0372.xml,immediately before 2,enables,opposite to 2
4,4,AFP_ENG_20100414.0615-E5,parole(contexts: A former militant of the Fren...,Justice_Release-Parole,AFP_ENG_20100414.0615-E13,murder(contexts: Cipriani was one of four memb...,Life_Die,AFP_ENG_20030519.0372.xml,immediately before 2,enables,NaN
...,...,...,...,...,...,...,...,...,...,...,...
443,443,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030304.0250.xml,meets 2,NaN,NaN
444,444,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV3,"EasyCinema founder Stelios Haji-Ioannou, who ...",Justice.Sue,AFP_ENG_20030304.0250.xml,enables,meets 2,NaN
445,445,AFP_ENG_20030509.0345-EV1,A ground-breaking British budget cinema chain...,Business.Start-Org,AFP_ENG_20030509.0345-EV4,debut of easyCinema's first outlet in Milton ...,Business.Start-Org,AFP_ENG_20030304.0250.xml,True/Related/Expansion.Conjunction/Relative/Ge...,NaN,NaN
446,446,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030509.0345-EV3,"EasyCinema founder Stelios Haji-Ioannou, who ...",Justice.Sue,AFP_ENG_20030304.0250.xml,True/Related/Inheritance.Subevent/Relative/Des...,contains 2,NaN
447,447,AFP_ENG_20030509.0345-EV2,"EasyCinema founder Stelios Haji-Ioannou, who ...",Business.Start-Org,AFP_ENG_20030509.0345-EV4,debut of easyCinema's first outlet in Milton ...,Business.Start-Org,AFP_ENG_20030304.0250.xml,enables 2,immediately before,NaN

In [20]:
file=pd.read_csv('mapped_data.csv', sep='\t')

In [21]:
file['rel1']

0                                                meets 2
1                                   immediately before 2
2                                               starts 2
3                                   immediately before 2
4                                   immediately before 2
                             ...
443                                              meets 2
444                                              enables
445    True/Related/Expansion.Conjunction/Relative/Ge...
446    True/Related/Inheritance.Subevent/Relative/Des...
447                                            enables 2
Name: rel1, Length: 448, dtype: object